Auth refactor
TLN1/tln-back pull request #8
Opened 2023-06-04 17:46 UTC by ninikh

remove application context from service layer
authorize user at api level
hash passwords
oauth2 with password, bearer jwt token flow

2023-06-05 18:25 UTC, LevanSamadashvili requested changes

2023-06-05 18:25 UTC, LevanSamadashvili commented on app/core/services/application_service.py
> -        if not self.application_repository.has_application(id=id):
add this back in :))) <3

2023-06-05 18:25 UTC, LevanSamadashvili commented on app/infra/application_context.py
> +        if not self.__verify_password(password, user.password):
barem hash_verifier gamogedzaxebinaaa :Ddd ragat gindoda is __verify_password

2023-06-05 18:53 UTC, LevanSamadashvili approved these changes

2023-06-12 08:01 UTC, tmike19 reviewed
+

2023-06-12 08:01 UTC, merged